### ISSUE TITLE
Jeopardy Ideen

### ISSUE THREAD

**Issue by jzaefferer** [signup-from-bandname/signup-from-hell#4]
Label: "A game show where the answer is the question"
Correct input: "What is Jeopardy?"

Mehr fällt mir nicht ein, das ist überraschend schwierig.

**Comment by soophie** [comment]
http://www.sproglaererforeningen.dk/cms/uploads/sproglaereren/2011-4/Station_11_Bilag_Jeopardy_spoergsmaal_med_svar.pdf

**Comment by jzaefferer** [comment]
Habe mir das PDF angeschaut, aber hat mir auch nicht geholfen. Ich mach mal zu, scheint keine gute Idee zu sein. Wir haben ja genug andere.
